// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6b
//
// <auto-generated>
//
// Generated from file `FileTransfer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __E__iflytek_IceFtp_IceFtpServer_FileTransfer_h__
#define __E__iflytek_IceFtp_IceFtpServer_FileTransfer_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION  != 30651
#       error Ice version mismatch: an exact match is required for beta generated code
#   endif
#endif

namespace IceProxy
{

namespace Cathy
{

class FileTransfer;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Cathy::FileTransfer>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Cathy::FileTransfer*);

}

}

namespace Cathy
{

class FileTransfer;
bool operator==(const FileTransfer&, const FileTransfer&);
bool operator<(const FileTransfer&, const FileTransfer&);
::Ice::Object* upCast(::Cathy::FileTransfer*);
typedef ::IceInternal::Handle< ::Cathy::FileTransfer> FileTransferPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Cathy::FileTransfer> FileTransferPrx;
void __patch(FileTransferPtr&, const ::Ice::ObjectPtr&);

}

namespace Cathy
{

typedef ::std::vector< ::Ice::Byte> ByteSeq;

}

namespace Cathy
{

class Callback_FileTransfer_read_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_FileTransfer_read_Base> Callback_FileTransfer_readPtr;

class Callback_FileTransfer_write_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_FileTransfer_write_Base> Callback_FileTransfer_writePtr;

}

namespace IceProxy
{

namespace Cathy
{

class FileTransfer : virtual public ::IceProxy::Ice::Object
{
public:

    ::Cathy::ByteSeq read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num)
    {
        return read(name, offset, num, 0);
    }
    ::Cathy::ByteSeq read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::Ice::Context& __ctx)
    {
        return read(name, offset, num, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::IceInternal::Function<void (const ::Cathy::ByteSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_read(name, offset, num, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_read(name, offset, num, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Cathy::ByteSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_read(name, offset, num, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_read(name, offset, num, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Cathy::ByteSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num)
    {
        return begin_read(name, offset, num, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::Ice::Context& __ctx)
    {
        return begin_read(name, offset, num, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_read(name, offset, num, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_read(name, offset, num, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::Cathy::Callback_FileTransfer_readPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_read(name, offset, num, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::Ice::Context& __ctx, const ::Cathy::Callback_FileTransfer_readPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_read(name, offset, num, &__ctx, __del, __cookie);
    }

    ::Cathy::ByteSeq end_read(const ::Ice::AsyncResultPtr&);
    
private:

    ::Cathy::ByteSeq read(const ::std::string&, ::Ice::Int, ::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_read(const ::std::string&, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes)
    {
        write(name, offset, bytes, 0);
    }
    void write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::Ice::Context& __ctx)
    {
        write(name, offset, bytes, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_write(name, offset, bytes, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_write(name, offset, bytes, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_write(name, offset, bytes, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_write(name, offset, bytes, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes)
    {
        return begin_write(name, offset, bytes, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::Ice::Context& __ctx)
    {
        return begin_write(name, offset, bytes, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_write(name, offset, bytes, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_write(name, offset, bytes, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::Cathy::Callback_FileTransfer_writePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_write(name, offset, bytes, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::Ice::Context& __ctx, const ::Cathy::Callback_FileTransfer_writePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_write(name, offset, bytes, &__ctx, __del, __cookie);
    }

    void end_write(const ::Ice::AsyncResultPtr&);
    
private:

    void write(const ::std::string&, ::Ice::Int, const ::Cathy::ByteSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_write(const ::std::string&, ::Ice::Int, const ::Cathy::ByteSeq&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_secure(bool __secure) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_twoway() const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_oneway() const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_batchOneway() const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_datagram() const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_batchDatagram() const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_compress(bool __compress) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_timeout(int __timeout) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<FileTransfer> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<FileTransfer*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace Cathy
{

class FileTransfer : virtual public ::Ice::Object
{
public:

    typedef FileTransferPrx ProxyType;
    typedef FileTransferPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::Cathy::ByteSeq read(const ::std::string&, ::Ice::Int, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___read(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void write(const ::std::string&, ::Ice::Int, const ::Cathy::ByteSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___write(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const FileTransfer& l, const FileTransfer& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const FileTransfer& l, const FileTransfer& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Cathy
{

template<class T>
class CallbackNC_FileTransfer_read : public Callback_FileTransfer_read_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Cathy::ByteSeq&);

    CallbackNC_FileTransfer_read(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Cathy::FileTransferPrx __proxy = ::Cathy::FileTransferPrx::uncheckedCast(__result->getProxy());
        ::Cathy::ByteSeq __ret;
        try
        {
            __ret = __proxy->end_read(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_FileTransfer_readPtr
newCallback_FileTransfer_read(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Cathy::ByteSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileTransfer_read<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_FileTransfer_readPtr
newCallback_FileTransfer_read(T* instance, void (T::*cb)(const ::Cathy::ByteSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileTransfer_read<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_FileTransfer_read : public Callback_FileTransfer_read_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Cathy::ByteSeq&, const CT&);

    Callback_FileTransfer_read(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Cathy::FileTransferPrx __proxy = ::Cathy::FileTransferPrx::uncheckedCast(__result->getProxy());
        ::Cathy::ByteSeq __ret;
        try
        {
            __ret = __proxy->end_read(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_FileTransfer_readPtr
newCallback_FileTransfer_read(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Cathy::ByteSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileTransfer_read<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_FileTransfer_readPtr
newCallback_FileTransfer_read(T* instance, void (T::*cb)(const ::Cathy::ByteSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileTransfer_read<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_FileTransfer_write : public Callback_FileTransfer_write_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_FileTransfer_write(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_FileTransfer_writePtr
newCallback_FileTransfer_write(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileTransfer_write<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_FileTransfer_writePtr
newCallback_FileTransfer_write(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileTransfer_write<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_FileTransfer_writePtr
newCallback_FileTransfer_write(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileTransfer_write<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_FileTransfer_writePtr
newCallback_FileTransfer_write(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileTransfer_write<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_FileTransfer_write : public Callback_FileTransfer_write_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_FileTransfer_write(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_FileTransfer_writePtr
newCallback_FileTransfer_write(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileTransfer_write<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_FileTransfer_writePtr
newCallback_FileTransfer_write(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileTransfer_write<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_FileTransfer_writePtr
newCallback_FileTransfer_write(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileTransfer_write<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_FileTransfer_writePtr
newCallback_FileTransfer_write(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileTransfer_write<T, CT>(instance, 0, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
