// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6b
//
// <auto-generated>
//
// Generated from file `FileTransfer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <FileTransfer.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION  != 30651
#       error Ice version mismatch: an exact match is required for beta generated code
#   endif
#endif

namespace
{

const ::std::string __Cathy__FileTransfer__read_name = "read";

const ::std::string __Cathy__FileTransfer__write_name = "write";

}
::IceProxy::Ice::Object* ::IceProxy::Cathy::upCast(::IceProxy::Cathy::FileTransfer* p) { return p; }

void
::IceProxy::Cathy::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Cathy::FileTransfer>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Cathy::FileTransfer;
        v->__copyFrom(proxy);
    }
}

::Cathy::ByteSeq
IceProxy::Cathy::FileTransfer::read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__Cathy__FileTransfer__read_name);
    ::IceInternal::Outgoing __og(this, __Cathy__FileTransfer__read_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(name);
        __os->write(offset);
        __os->write(num);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::Cathy::ByteSeq __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::Cathy::FileTransfer::begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Cathy__FileTransfer__read_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Cathy__FileTransfer__read_name, __del, __cookie);
    try
    {
        __result->prepare(__Cathy__FileTransfer__read_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(name);
        __os->write(offset);
        __os->write(num);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::Cathy::FileTransfer::__begin_read(const ::std::string& name, ::Ice::Int offset, ::Ice::Int num, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Cathy::ByteSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::Cathy::ByteSeq&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::Cathy::FileTransferPrx __proxy = ::Cathy::FileTransferPrx::uncheckedCast(__result->getProxy());
            ::Cathy::ByteSeq __ret;
            try
            {
                __ret = __proxy->end_read(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (const ::Cathy::ByteSeq&)> _response;
    };
    return begin_read(name, offset, num, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::Cathy::ByteSeq
IceProxy::Cathy::FileTransfer::end_read(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Cathy__FileTransfer__read_name);
    ::Cathy::ByteSeq __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

void
IceProxy::Cathy::FileTransfer::write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __Cathy__FileTransfer__write_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(name);
        __os->write(offset);
        __os->write(bytes);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::Cathy::FileTransfer::begin_write(const ::std::string& name, ::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Cathy__FileTransfer__write_name, __del, __cookie);
    try
    {
        __result->prepare(__Cathy__FileTransfer__write_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(name);
        __os->write(offset);
        __os->write(bytes);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::Cathy::FileTransfer::end_write(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Cathy__FileTransfer__write_name);
}

const ::std::string&
IceProxy::Cathy::FileTransfer::ice_staticId()
{
    return ::Cathy::FileTransfer::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::Cathy::FileTransfer::__newInstance() const
{
    return new FileTransfer;
}

::Ice::Object* Cathy::upCast(::Cathy::FileTransfer* p) { return p; }

namespace
{
const ::std::string __Cathy__FileTransfer_ids[2] =
{
    "::Cathy::FileTransfer",
    "::Ice::Object"
};

}

bool
Cathy::FileTransfer::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Cathy__FileTransfer_ids, __Cathy__FileTransfer_ids + 2, _s);
}

::std::vector< ::std::string>
Cathy::FileTransfer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Cathy__FileTransfer_ids[0], &__Cathy__FileTransfer_ids[2]);
}

const ::std::string&
Cathy::FileTransfer::ice_id(const ::Ice::Current&) const
{
    return __Cathy__FileTransfer_ids[0];
}

const ::std::string&
Cathy::FileTransfer::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Cathy::FileTransfer";
    return typeId;
#else
    return __Cathy__FileTransfer_ids[0];
#endif
}

::Ice::DispatchStatus
Cathy::FileTransfer::___read(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string name;
    ::Ice::Int offset;
    ::Ice::Int num;
    __is->read(name);
    __is->read(offset);
    __is->read(num);
    __inS.endReadParams();
    ::Cathy::ByteSeq __ret = read(name, offset, num, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Cathy::FileTransfer::___write(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string name;
    ::Ice::Int offset;
    ::Cathy::ByteSeq bytes;
    __is->read(name);
    __is->read(offset);
    __is->read(bytes);
    __inS.endReadParams();
    write(name, offset, bytes, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Cathy__FileTransfer_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "read",
    "write"
};

}

::Ice::DispatchStatus
Cathy::FileTransfer::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Cathy__FileTransfer_all, __Cathy__FileTransfer_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Cathy__FileTransfer_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___read(in, current);
        }
        case 5:
        {
            return ___write(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Cathy::FileTransfer::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Cathy::FileTransfer::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Cathy::__patch(FileTransferPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Cathy::FileTransferPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Cathy::FileTransfer::ice_staticId(), v);
    }
}
