// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6b
//
// <auto-generated>
//
// Generated from file `FileTransfer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <FileTransfer.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION  != 30651
#       error Ice version mismatch: an exact match is required for beta generated code
#   endif
#endif

namespace
{

const ::std::string __Cathy__FileTransfer__send_name = "send";

}
::IceProxy::Ice::Object* ::IceProxy::Cathy::upCast(::IceProxy::Cathy::FileTransfer* p) { return p; }

void
::IceProxy::Cathy::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Cathy::FileTransfer>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Cathy::FileTransfer;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Cathy::FileTransfer::send(::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __Cathy__FileTransfer__send_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(offset);
        __os->write(bytes);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::Cathy::FileTransfer::begin_send(::Ice::Int offset, const ::Cathy::ByteSeq& bytes, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Cathy__FileTransfer__send_name, __del, __cookie);
    try
    {
        __result->prepare(__Cathy__FileTransfer__send_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(offset);
        __os->write(bytes);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::Cathy::FileTransfer::end_send(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Cathy__FileTransfer__send_name);
}

const ::std::string&
IceProxy::Cathy::FileTransfer::ice_staticId()
{
    return ::Cathy::FileTransfer::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::Cathy::FileTransfer::__newInstance() const
{
    return new FileTransfer;
}

::Ice::Object* Cathy::upCast(::Cathy::FileTransfer* p) { return p; }

namespace
{
const ::std::string __Cathy__FileTransfer_ids[2] =
{
    "::Cathy::FileTransfer",
    "::Ice::Object"
};

}

bool
Cathy::FileTransfer::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Cathy__FileTransfer_ids, __Cathy__FileTransfer_ids + 2, _s);
}

::std::vector< ::std::string>
Cathy::FileTransfer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Cathy__FileTransfer_ids[0], &__Cathy__FileTransfer_ids[2]);
}

const ::std::string&
Cathy::FileTransfer::ice_id(const ::Ice::Current&) const
{
    return __Cathy__FileTransfer_ids[0];
}

const ::std::string&
Cathy::FileTransfer::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Cathy::FileTransfer";
    return typeId;
#else
    return __Cathy__FileTransfer_ids[0];
#endif
}

::Ice::DispatchStatus
Cathy::FileTransfer::___send(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Int offset;
    ::Cathy::ByteSeq bytes;
    __is->read(offset);
    __is->read(bytes);
    __inS.endReadParams();
    send(offset, bytes, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Cathy__FileTransfer_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "send"
};

}

::Ice::DispatchStatus
Cathy::FileTransfer::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Cathy__FileTransfer_all, __Cathy__FileTransfer_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Cathy__FileTransfer_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___send(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Cathy::FileTransfer::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Cathy::FileTransfer::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Cathy::__patch(FileTransferPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Cathy::FileTransferPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Cathy::FileTransfer::ice_staticId(), v);
    }
}
